name: EvoleMe
favicon: null
layout_spectrum: 0.75308
typography_spectrum: 0.23505
title: EvolveME
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5
  lightness: 0.9509195175487548
  saturation: 0.4375
  rhythmicContrast: 0.7113515720702708
purpose: []
